services:
  - type: web
    name: vtc-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: ./server
    envVars:
      - key: NODE_ENV
        value: production
